### ISSUE TITLE
General comparison of 1.5 and 2.0 block hashes matching

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/telosevm-translator#11]
## Overview

The goal is to import some blocks into Silkworm and make sure that block hashes at some height (depending on the amount of transactions) are still the same. 

## Acceptance criteria

- Block hash match 2.0 and works seamlessly
- Match up to 200M considering all the fields, not only the block hash

## Technical considerations

Consider that we are using **EVMONE** as the execution engine because of time constraints. 

## Tasks

- [x] Successfully import roughly 10 million blocks into Silkworm
- [x] Mapping between EOS address and related EVM address (temporary until we get the data from nodeos) 
- [x] Check the for any differences between the blocks with @guilledk 
- [x] Successfully handle the native signed transaction in 2.0
- [x] Fix difference in initial nonce
- [x] Fix difference between gas on some blocks
